### ISSUE TITLE
Roadmap planning for Iteration 01

### ISSUE THREAD

**Issue by slpycatzz** [C-YanHua/CS3201-T04#1]
# Parser
- [x] Support parsing of one procedure (dc9361a648da0ede60b8b69f0b7e1f2264241052)
- [x] Support parsing of while statements (dc9361a648da0ede60b8b69f0b7e1f2264241052)
- [x] Support parsing of assignment statements that contains expressions with '+' (dc9361a648da0ede60b8b69f0b7e1f2264241052)
- [x] Able to handle possible of '\\' comments in line and ignore it (dc9361a648da0ede60b8b69f0b7e1f2264241052, c09bafb7860a4645e3853dbe3a62da64bd6129ac)
- [x] Able to catch missing or extra curly brackets error (dc9361a648da0ede60b8b69f0b7e1f2264241052)
- [x] Able to catch unsupported syntax error (Example: divide is not allowed in assignment) (dc9361a648da0ede60b8b69f0b7e1f2264241052)
- [x] Able to catch empty statement list error (dc9361a648da0ede60b8b69f0b7e1f2264241052)
# PKB
- [x] Implement APIs for parser to generate an AST. (dc9361a648da0ede60b8b69f0b7e1f2264241052)
- [x] Implement an API for parser to generate a ConstantTable. (b8b1ad96eb786696b3a8935623694fe0c72918a8)
- [x] Implement an API for parser to generate a VariableTable. (b8b1ad96eb786696b3a8935623694fe0c72918a8)
- [x] Implement an API for parser to generate a ProcedureTable. (b8b1ad96eb786696b3a8935623694fe0c72918a8)
- [x] Implement an API for parser to generate a StmtTable. (b8b1ad96eb786696b3a8935623694fe0c72918a8)
- [x] Implement an API for parser to generate an AssignTable. (7f62a109663ed5dfe705f9a5ee2e2068097ea4ba)
- [x] Implement an API for parser to generate a ModifiesTable. (44ee8ea24aa741927e250fdafad8ba39f0a18cce)
- [x] Implement an API for parser to generate a UsesTable. (83b32eefcb62a220b271af5b9c60c8fb15b6efed)
- [x] Implement an API for parser to generate a FollowsTable. (e6f0d61f52aee32b440b9704b3d56263d15e32c1)
- [x] Implement an API for parser to generate a ParentTable. (f57a620a8b74f7d2dd184d3720cc5b36524231d7)
- [x] Implement an API for PKB to generate a ParentTransitiveTable from ParentTable. (256db56a9100c76532c3985dffa3985db43a7784)
- [x] Implement an API for PKB to generate a FollowsTransitiveTable from FollowsTable. (e6f0d61f52aee32b440b9704b3d56263d15e32c1)
- [x] Implement APIs for query processor to interact with AssignTable for pattern matching. (7f62a109663ed5dfe705f9a5ee2e2068097ea4ba)
- [x] Implement APIs for query processor to retrieve "Modifies" design abstraction. (15c7fb4fed260322abc396cfa7d751d3cc1d70ca)
- [x] Implement APIs for query processor to retrieve "Uses" design abstraction. (15c7fb4fed260322abc396cfa7d751d3cc1d70ca)
- [x] Implement APIs for query processor to retrieve "Parent" design abstraction. (15c7fb4fed260322abc396cfa7d751d3cc1d70ca)
- [x] Implement APIs for query processor to retrieve "ParentTransitive" design abstraction. (15c7fb4fed260322abc396cfa7d751d3cc1d70ca)
- [x] Implement APIs for query processor to retrieve "Follows" design abstraction. (15c7fb4fed260322abc396cfa7d751d3cc1d70ca)
- [x] Implement APIs for query processor to retrieve "FollowsTransitive" design abstraction. (15c7fb4fed260322abc396cfa7d751d3cc1d70ca)
# Query Processor
- [x] Supports a minimum of one "such that" clause.
- [x] Supports a minimum of one "pattern" clause.
- [x] Supports a minimum of one common synonym between two clauses.
- [x] Query pre-processor supports parsing of query.
- [x] Query pre-processor supports validation of query.
- [x] Query pre-processor supports constructing of query tree from query.
- [x] Query Evaluator is able to process the query tree and query PKB for appropriate design abstraction.
# Documentation

The task list is breakdown into different sections needed in the documentation.
- [x] Development Plan
- [x] Scope of the prototype implementation
- [x] SPA Design
- [x] Documentation and Coding Standards
- [x] Testing
- [x] Discussion
- [x] Documentation of Abstract APIs
# Tests
- [x] Minimum three sample test cases (three SIMPLE program and three queries) (e8014d2b29a79a1e9403b1a0c23763f8ecb0cf20)
- [x] Parser Unit Testing
- [x] PQL Unit Testing
- [x] Query Processor Unit Testing
- [x] Parser and PQL Integration Testing
- [x] Query Processer Integration Testing
- [x] System Testing (Using AutoTester)
