### ISSUE TITLE
Roadmap planning for Iteration 03

### ISSUE THREAD

**Issue by slpycatzz** [C-YanHua/CS3201-T04#15]
# PKB
- [x] Implement APIs for query processor to retrieve "Affects" design abstraction.
# Query Processor
- [x] Improve optimization strategy.
- [x] Refactor and clean-up query evaluator code.
- [x] Refactor and clean-up query preprocessor code.
# Documentation
- [x] Development Plan
- [x] Scope of the prototype implementation
- [x] SPA Design
- [x] Documentation and Coding Standards
- [x] Testing
- [x] Discussion
- [x] Documentation of Abstract APIs
# Tests
- [x] System Testing (Using AutoTester)
