### ISSUE TITLE
Roadmap planning for Iteration 02

### ISSUE THREAD

**Issue by slpycatzz** [C-YanHua/CS3201-T04#9]
# Parser
- [x] Support parsing of call statements. (dc9361a648da0ede60b8b69f0b7e1f2264241052)
- [x] Support parsing of if/else statements. (dc9361a648da0ede60b8b69f0b7e1f2264241052)
- [x] Support parsing of assignment statements that contains expressions with '+', '-' and '*'. (dc9361a648da0ede60b8b69f0b7e1f2264241052)
- [x] Support parsing of multiple procedures. (e50c0ec4525b536992698f94efeffa6b666dbece)
- [x] Able to catch recursive procedure call check. (e50c0ec4525b536992698f94efeffa6b666dbece)
- [x] Able to catch duplicate procedure name. (e50c0ec4525b536992698f94efeffa6b666dbece)
- [x] Able to catch non-existent procedure call. (e50c0ec4525b536992698f94efeffa6b666dbece)
# PKB
- [x] Implement APIs for parser to generate a CFG. (1d87a1a10d0097f1f9f83adcf62b1f5bfe33489c)
- [x] Revamp the AssignTable and its APIs to store a string of the whole assign expression in a proper form instead of the node to allow Query Evaluator to evaluate expressions much more easily. (5e5573890c801ec32d9e0a490bbb1b56e22370fb) (76317156b16abb23d6f8796901067a89d3fef748)
- [x] Improve ModifiesTable to support multiple procedures and call statements. (e50c0ec4525b536992698f94efeffa6b666dbece)
- [x] Improve UsesTable to support multiple procedures and call statements. (e50c0ec4525b536992698f94efeffa6b666dbece)
- [x] Implement an API for parser to generate a CallsTable. (e50c0ec4525b536992698f94efeffa6b666dbece)
- [x] Implement an API for PKB to generate a CallsTransitiveTable from CallTable. (e50c0ec4525b536992698f94efeffa6b666dbece)
- [x] Implement an API for parser to generate a NextTable. (60aa28ea7dd8c9111284a51492e1dc875e89cd36)
- [x] Implement an API for PKB to compute NextTransitive queries on demand. (1d87a1a10d0097f1f9f83adcf62b1f5bfe33489c)
- [x] Implement APIs for query processor to retrieve "Calls" design abstraction. (e50c0ec4525b536992698f94efeffa6b666dbece)
- [x] Implement APIs for query processor to retrieve "Next" design abstraction.  (60aa28ea7dd8c9111284a51492e1dc875e89cd36) (1d87a1a10d0097f1f9f83adcf62b1f5bfe33489c)
# Query Processor
- [x] Supports multiple "such that" clause.
- [x] Supports multiple "pattern" clause.
- [x] Supports combination of "such that", "pattern" and "attributes" (stmt# = ...).
- [x] Supports multiple synonyms appearing between multiple clauses.
- [x] Supports query optimizing.
- [x] Improve on query preprocessor query validation. (Catch more possible invalid cases)
- [x] Refactor and clean-up query preprocessor code.
# Documentation

The task list is breakdown into different sections needed in the documentation.
Any changes from iteration 1 to iteration 2 is to be documented accordingly.
- [x] Development Plan
- [x] Scope of the prototype implementation
- [x] SPA Design
- [x] Documentation and Coding Standards
- [x] Testing
- [x] Discussion
- [x] Documentation of Abstract APIs
# Tests
- [x] Parser Unit Testing
- [x] PKB Unit Testing
- [x] PQL Unit Testing
- [x] Query preprocessor Unit Testing
- [x] Query evaluator Unit Testing
- [x] Query optimizer Unit Testing
- [x] PKB Integration Testing
- [x] Query Processor Integration Testing
- [x] System Testing (Using AutoTester)
